### ISSUE TITLE
Thresholded maps: binarize -> resample

### ISSUE THREAD

**Issue by glatard** [poldrack/narps#28]
Minor comment: I'm wondering if binarization of thresholded maps should happen after they have been resampled, as resampling a binary mask may not always produce a binary mask. This might be related to the thresholding done after resampling the thresholded maps, which looks a bit suspicious to me:
https://github.com/glatard/narps/blob/5628cef4bcd5694475720456ec48c0741c21e3de/ImageAnalyses/narps.py#L347-L351

**Comment by poldrack** [comment]
the issue is as follows: we were provided with thresholded maps by the investigators, so we don't have a way to independently generate them from the unthresholded maps.  thus, we have to resample the thresholded maps into the common space.  I originally did this using nearest neighbor interopolation, but that resulted in artifacts in some images such that adjacent voxels were mapped to the same voxel in the output, leaving some empty voxels.  To avoid this, we use linear interpolation and then threshold the resulting interpolated version of the binarized map at >0.5.  let me know if that sounds sensible.
