### ISSUE TITLE
concat_thresh directory

### ISSUE THREAD

**Issue by glatard** [poldrack/narps#30]
Output directory `concat_thresh` remains empty after my local execution of the pipeline. Tracking it through the code, I'm not sure how it gets used in `create_thresh_overlap_images`:
https://github.com/poldrack/narps/blob/c6040140573002c4d934046836c2ac1073f51dcc/ImageAnalyses/narps.py#L589-L591
I must be missing something since `create_thresh_overlap_images` still produces a plausible result, but can't figure out what.

**Comment by poldrack** [comment]
this took me a bit to figure out. I think what is happening is that self.dirs.dirs['concat_thresh'] is getting renamed to .../thresh_concat_resampled at line 529.  so it ends up violating the unwritten assumption here that the dictionary key matches the actual directory name. I will rewrite this so that the dict keys always match the directory name, to prevent confusion.

**Comment by poldrack** [comment]
ok, should be fixed in commits leading up to 3a3218e
