### ISSUE TITLE
Ordering of teams

### ISSUE THREAD

**Issue by glatard** [poldrack/narps#33]
The analysis heavily relies on the sorting of team ids, and this sorting is done in two different places:

Here:

https://github.com/poldrack/narps/blob/c6040140573002c4d934046836c2ac1073f51dcc/ImageAnalyses/utils.py#L59

and there:

https://github.com/poldrack/narps/blob/c6040140573002c4d934046836c2ac1073f51dcc/ImageAnalyses/narps.py#L447

I'm 99.9% sure that both orders will be identical, but given that a different ordering would puzzle the analysis quite a bit, it would be safe to double check that.

**Comment by poldrack** [comment]
added a test in eb306a4 to ensure that the ordering of the labels returned by get_masked_data is identical to narps.complete_image_sets

**Comment by poldrack** [comment]
reopening this - my approach failed because complete_image_sets is based on thresh and there is one team with thresh but no unthresh.  need to find another solution.

**Comment by poldrack** [comment]
ok, new solution: instead of reloading individual images, I use the concatenated data files for these analyses, and I save a label file when creating the concat images that includes provenance of the concat data.  replace get_masked_data() with get_concat_data() to do this.  see commits leading up to a6cc56c
